//If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
//Find the sum of all the multiples of 3 or 5 below 1000.*/+

var sum = 0;

var threeAndFive = function() {
    for (var i=0; i<1000; i++) {
        if(i%3 === 0 || i%5 === 0) {
            sum +=i;
            console.log(i, sum) 
            }
    }
}

// ### done ### 
//next


//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var sum = 0;
var arr = [1,2];
var firstFib = 1;
var secondFib = 2;

var fb = function() {
    while(secondFib <= 4000000) {
        secondFib += firstFib;
        firstFib = secondFib - firstFib;
       // console.log(firstFib, secondFib);
        arr.push(secondFib);
       // console.log(arr);
        
    }
    for (var i = 0; i < arr.length; i++) {
        if (arr[i]%2 === 0) {
            sum += arr[i];
            //console.log(sum);
        }
    }
    return sum;
}

// ### returns correct answer :-) ###
// next


//The prime factors of 13195 are 5, 7, 13 and 29.
//What is the largest prime factor of the number 600851475143 ?



