//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var sum = 0;
var arr = [];
var firstFib = 1;
var secondFib = 2;

var fb = function() {
    while(secondFib <= 4000000) {
        secondFib += firstFib;
        firstFib = secondFib;
        console.log(firstFib, secondFib);
        
    }
}
// ### done and working correctly ### 

